theme: minima

# Name of your site (displayed in the header)
name: Mizuki
title: Mizuki

# Short bio or description (displayed in the header)
description: Random, non-professional odds and ends
