theme: minima

# Name of your site (displayed in the header)
name: Mizuki
title: Mizuki

# Short bio or description (displayed in the header)
description: Random, non-professional thoughts

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
